import type { TableData, TableStyle, Cell, BorderStyle } from '$lib/types';
import { escapeLatexText } from './latex-processor';

// --- Constants ---

// 像素到 pt 的转换比例 (假设 96 DPI)
const PX_TO_PT = 0.75;

// Padding 映射 (与 AcademicTable 保持一致)
const PADDING_MAP: Record<string, number> = {
    compact: 4,
    normal: 8,
    loose: 16
};

// --- Helpers ---

function formatColor(hex: string): string {
    return hex.replace('#', '');
}

/**
 * 将像素转换为 pt
 */
function pxToPt(px: number): number {
    return Math.round(px * PX_TO_PT);
}

/**
 * 根据 BorderStyle 生成 booktabs 的线型命令
 */
function getBorderCommand(borderStyle: BorderStyle, position: 'top' | 'bottom' | 'header'): string {
    switch (borderStyle) {
        case 'none':
            return '';
        case 'thin':
            return position === 'header' ? '\\midrule' : (position === 'top' ? '\\toprule' : '\\bottomrule');
        case 'thick':
            return position === 'header' ? '\\midrule' : (position === 'top' ? '\\toprule' : '\\bottomrule');
        case 'double':
            return position === 'header' ? '\\midrule\\midrule' : (position === 'top' ? '\\toprule\\toprule' : '\\bottomrule\\bottomrule');
        case 'thick-thin':
            // 粗线 + 细线，用于顶部
            return '\\toprule\\midrule';
        case 'thin-thick':
            // 细线 + 粗线，用于底部
            return '\\midrule\\bottomrule';
        default:
            return '\\hline';
    }
}

/**
 * 渲染单元格内部内容（处理转义、粗体、斜体、文字颜色）
 * 注意：换行处理在 wrapWithMakecell 中进行
 */
function renderCellContent(cell: Cell): string {
    let content = cell.content;

    // 1. 转义或保留公式
    if (!(content.startsWith('$') && content.endsWith('$'))) {
        content = escapeLatexText(content);
    }

    // 不在这里应用样式，样式在 wrapWithMakecell 中按行应用
    return content;
}

/**
 * 对单行内容应用样式（粗体、斜体、颜色）
 */
function applyStyles(content: string, cell: Cell): string {
    let result = content;
    if (cell.isBold) result = `\\textbf{${result}}`;
    if (cell.isItalic) result = `\\textit{${result}}`;
    if (cell.textColor) {
        result = `\\textcolor[HTML]{${formatColor(cell.textColor)}}{${result}}`;
    }
    return result;
}

/**
 * 处理单元格内换行：如果有换行，用 makecell 包裹
 * 样式需要对每一行分别应用，否则 \\ 在样式命令内部不会正确换行
 */
function wrapWithMakecell(cell: Cell, content: string, cellPaddingPt: number): string {
    if (!cell.content.includes('\n')) {
        // 没有换行，直接应用样式
        return applyStyles(content, cell);
    }
    
    // 有换行，需要对每一行分别应用样式
    const lines = content.split('\n');
    const styledLines = lines.map(line => applyStyles(line, cell));
    const alignChar = cell.align ? cell.align[0] : 'c';
    
    // makecell 内部不需要额外间距，因为 \makegapedcells 已经处理了单元格间距
    // 但需要禁用 makegapedcells 对这个单元格的影响，用 \nommark 或直接用原始 makecell
    const innerContent = styledLines.join(' \\\\ ');
    return `\\makecell[${alignChar}]{${innerContent}}`;
}

/**
 * 将内容包裹在布局命令中（处理 colspan, rowspan, cellcolor, align）
 */
function wrapWithLayout(cell: Cell, innerContent: string): string {
    const { colspan = 1, rowspan = 1, backgroundColor, align } = cell;

    // 准备组件
    const cellColorCmd = backgroundColor
        ? `\\cellcolor[HTML]{${formatColor(backgroundColor)}}`
        : '';
    const alignChar = align ? align[0] : 'c'; // 默认为 c

    // 组合逻辑
    let finalLatex = innerContent;

    // 1. 处理 Rowspan
    if (rowspan > 1) {
        // \multirow{row}{width}{content}
        finalLatex = `\\multirow{${rowspan}}{*}{${finalLatex}}`;
    }

    // 2. 处理 Colspan 或 强制对齐 或 带有背景色
    // 只要有 colspan, 或者有特定对齐, 或者有背景色(为了安全起见), 我们都用 multicolumn
    const needsMulticolumn = colspan > 1 || align || backgroundColor;

    if (needsMulticolumn) {
        // 关键：背景色通常放在 multicolumn 内部单元格的最前面
        // \multicolumn{nums}{align}{ \cellcolor{...} Content }
        finalLatex = `\\multicolumn{${colspan}}{${alignChar}}{${cellColorCmd}${finalLatex}}`;
    } else {
        // 如果完全没有特殊布局，直接返回（如果有背景色但没进上面分支，说明逻辑有问题，但这里 needsMulticolumn 覆盖了）
        // 如果只有背景色，没有 colspan，我们也推荐用 multicolumn{1} 包裹以隔离样式
        finalLatex = `${cellColorCmd}${finalLatex}`;
    }

    return finalLatex;
}


// --- Main ---

export function generateLatexTable(data: TableData, style: TableStyle): string {
    const { rows, headerRows } = data;
    const { preset, borders, fontSize, padding } = style;
    const isBooktabs = preset === 'booktabs';

    // 计算 cell padding
    const cellPadding = typeof padding === 'number' ? padding : PADDING_MAP[padding] || 8;
    const cellPaddingPt = pxToPt(cellPadding);

    const output: string[] = [];

    // 1. Preamble
    output.push(
        '% Generated by Tablix',
        '\\documentclass{article}',
        '\\usepackage[utf8]{inputenc}',
        '\\usepackage{booktabs}',
        '\\usepackage[table]{xcolor}',
        '\\usepackage{amsmath}',
        '\\usepackage{multirow}',
        '\\usepackage{makecell}',
        '\\usepackage{array}',
        '\\usepackage{geometry}',
        '\\geometry{margin=1in}',
        ''
    );

    // 使用 makecell 的 setcellgapes 来设置上下间距
    output.push(`\\setcellgapes{${cellPaddingPt}pt}`);

    // 设置单元格左右内边距
    output.push(`\\setlength{\\tabcolsep}{${cellPaddingPt}pt}`);
    output.push('');

    output.push(
        '\\begin{document}',
        '',
        '\\begin{table}[h]',
        '\\centering',
        '\\makegapedcells'  // 启用单元格间距
    );

    // 设置字体大小
    if (fontSize !== 12) {
        output.push(`{\\fontsize{${fontSize}pt}{${Math.round(fontSize * 1.2)}pt}\\selectfont`);
    }

    // 2. Column Config - 使用 c 列类型
    const colCount = rows[0]?.length || 0;
    if (colCount > 0) {
        const colSpec = Array(colCount).fill('c').join('');
        output.push(`\\begin{tabular}{${colSpec}}`);
    } else {
        return '';
    }

    // 3. Top border
    const topBorderCmd = isBooktabs 
        ? getBorderCommand(borders.top, 'top')
        : '\\hline';
    if (topBorderCmd) {
        output.push(topBorderCmd);
    }

    // 追踪被 rowspan 占据的格子 "rowIndex-colIndex"
    const spannedMatrix = new Set<string>();

    for (let i = 0; i < rows.length; i++) {
        const row = rows[i];
        const rowCells: string[] = [];

        for (let j = 0; j < row.length; j++) {
            const cell = row[j];
            const coord = `${i}-${j}`;

            // Check 1: 是否被上方的 rowspan 占据 (Vertical Slave)
            if (spannedMatrix.has(coord)) {
                const bgCmd = cell.backgroundColor
                    ? `\\cellcolor[HTML]{${formatColor(cell.backgroundColor)}}`
                    : '';
                rowCells.push(bgCmd);
                continue;
            }

            // Check 2: 这是个新的有效单元格

            // 如果它有 rowspan，标记未来的格子
            if (cell.rowspan && cell.rowspan > 1) {
                const colspan = cell.colspan || 1;
                for (let r = 1; r < cell.rowspan; r++) {
                    const targetRow = i + r;
                    for (let c = 0; c < colspan; c++) {
                        const targetCol = j + c;
                        spannedMatrix.add(`${targetRow}-${targetCol}`);
                    }
                }
            }

            // 渲染内容
            let innerContent = renderCellContent(cell);
            innerContent = wrapWithMakecell(cell, innerContent, cellPaddingPt);
            const latexFragment = wrapWithLayout(cell, innerContent);
            rowCells.push(latexFragment);

            // Check 3: 如果它有 colspan，跳过当前行的后续格子
            if (cell.colspan && cell.colspan > 1) {
                j += cell.colspan - 1;
            }
        }

        output.push(rowCells.join(' & ') + ' \\\\');

        // Draw horizontal lines
        if (headerRows && i === headerRows - 1) {
            const headerBorderCmd = isBooktabs
                ? getBorderCommand(borders.headerBottom, 'header')
                : '\\hline';
            if (headerBorderCmd) {
                output.push(headerBorderCmd);
            }
        }
    }

    // 4. Bottom border
    const bottomBorderCmd = isBooktabs
        ? getBorderCommand(borders.bottom, 'bottom')
        : '\\hline';
    if (bottomBorderCmd) {
        output.push(bottomBorderCmd);
    }

    output.push('\\end{tabular}');
    
    // 关闭字体大小设置
    if (fontSize !== 12) {
        output.push('}');
    }

    output.push('\\end{table}', '', '\\end{document}');

    return output.join('\n');
}
