import type { TableData, TableStyle, Cell } from '$lib/types';
import { escapeLatexText } from './latex-processor';

// --- Helpers ---

function formatColor(hex: string): string {
    return hex.replace('#', '');
}

/**
 * 渲染单元格内部内容（处理转义、粗体、斜体、文字颜色）
 */
function renderCellContent(cell: Cell): string {
    let content = cell.content;

    // 1. 转义或保留公式
    if (!(content.startsWith('$') && content.endsWith('$'))) {
        content = escapeLatexText(content);
    }

    // 2. 样式修饰
    if (cell.isBold) content = `\\textbf{${content}}`;
    if (cell.isItalic) content = `\\textit{${content}}`;
    if (cell.textColor) {
        content = `\\textcolor[HTML]{${formatColor(cell.textColor)}}{${content}}`;
    }

    return content;
}

/**
 * 将内容包裹在布局命令中（处理 colspan, rowspan, cellcolor, align）
 */
function wrapWithLayout(cell: Cell, innerContent: string): string {
    const { colspan = 1, rowspan = 1, backgroundColor, align } = cell;

    // 准备组件
    const cellColorCmd = backgroundColor
        ? `\\cellcolor[HTML]{${formatColor(backgroundColor)}}`
        : '';
    const alignChar = align ? align[0] : 'c'; // 默认为 c

    // 组合逻辑
    let finalLatex = innerContent;

    // 1. 处理 Rowspan
    if (rowspan > 1) {
        // \multirow{row}{width}{content}
        finalLatex = `\\multirow{${rowspan}}{*}{${finalLatex}}`;
    }

    // 2. 处理 Colspan 或 强制对齐 或 带有背景色
    // 只要有 colspan, 或者有特定对齐, 或者有背景色(为了安全起见), 我们都用 multicolumn
    const needsMulticolumn = colspan > 1 || align || backgroundColor;

    if (needsMulticolumn) {
        // 关键：背景色通常放在 multicolumn 内部单元格的最前面
        // \multicolumn{nums}{align}{ \cellcolor{...} Content }
        finalLatex = `\\multicolumn{${colspan}}{${alignChar}}{${cellColorCmd}${finalLatex}}`;
    } else {
        // 如果完全没有特殊布局，直接返回（如果有背景色但没进上面分支，说明逻辑有问题，但这里 needsMulticolumn 覆盖了）
        // 如果只有背景色，没有 colspan，我们也推荐用 multicolumn{1} 包裹以隔离样式
        finalLatex = `${cellColorCmd}${finalLatex}`;
    }

    return finalLatex;
}


// --- Main ---

export function generateLatexTable(data: TableData, style: TableStyle): string {
    const { rows, headerRows } = data;
    const { preset } = style;
    const isBooktabs = preset === 'booktabs';

    const output: string[] = [];

    // 1. Preamble
    output.push(
        '% Generated by Tablix',
        '\\documentclass{article}',
        '\\usepackage[utf8]{inputenc}',
        '\\usepackage{booktabs}',
        '\\usepackage[table]{xcolor}',
        '\\usepackage{amsmath}',
        '\\usepackage{multirow}',
        '\\usepackage{geometry}',
        '\\geometry{margin=1in}',
        '',
        '\\begin{document}',
        '',
        '\\begin{table}[h]',
        '\\centering'
    );

    // 2. Column Config
    const colCount = rows[0]?.length || 0;
    if (colCount > 0) {
        // TODO: 支持列宽
        const colSpec = Array(colCount).fill('c').join('');
        output.push(`\\begin{tabular}{${colSpec}}`);
    } else {
        return '';
    }

    // 3. Table Rows
    output.push(isBooktabs ? '\\toprule' : '\\hline');

    // 追踪被 rowspan 占据的格子 "rowIndex-colIndex"
    const spannedMatrix = new Set<string>();

    for (let i = 0; i < rows.length; i++) {
        const row = rows[i];
        const rowCells: string[] = [];

        for (let j = 0; j < row.length; j++) {
            const cell = row[j];
            const coord = `${i}-${j}`;

            // Check 1: 是否被上方的 rowspan 占据 (Vertical Slave)
            if (spannedMatrix.has(coord)) {
                // 是垂直 slave，输出空占位符
                // 保持背景色以防断裂
                const bgCmd = cell.backgroundColor
                    ? `\\cellcolor[HTML]{${formatColor(cell.backgroundColor)}}`
                    : '';
                rowCells.push(bgCmd);
                continue; // 处理下一个单元格
            }

            // Check 2: 这是个新的有效单元格

            // 如果它有 rowspan，标记未来的格子
            if (cell.rowspan && cell.rowspan > 1) {
                const colspan = cell.colspan || 1;
                // 对于 rowspan 覆盖的每一行
                for (let r = 1; r < cell.rowspan; r++) {
                    const targetRow = i + r;
                    // 对于 colspan 覆盖的每一列 (rowspan 的格可能本身也是 colspan)
                    for (let c = 0; c < colspan; c++) {
                        const targetCol = j + c;
                        spannedMatrix.add(`${targetRow}-${targetCol}`);
                    }
                }
            }

            // 渲染内容
            const innerContent = renderCellContent(cell);
            const latexFragment = wrapWithLayout(cell, innerContent);
            rowCells.push(latexFragment);

            // Check 3: 如果它有 colspan，跳过当前行的后续格子 (Horizontal Slave)
            if (cell.colspan && cell.colspan > 1) {
                j += cell.colspan - 1;
            }
        }

        output.push(rowCells.join(' & ') + ' \\\\');

        // Draw horizontal lines
        if (headerRows && i === headerRows - 1) {
            output.push(isBooktabs ? '\\midrule' : '\\hline');
        } else if (!isBooktabs && i < rows.length - 1) {
            // Grid lines
        }
    }

    output.push(isBooktabs ? '\\bottomrule' : '\\hline');
    output.push('\\end{tabular}', '\\end{table}', '', '\\end{document}');

    return output.join('\n');
}
